# nse200_tickers.py
# ─────────────────────────────────────────────────────────────────────────────
# NSE 200 constituent tickers for yfinance download.
#
# RULES:
#   1. Every ticker MUST be downloadable via yfinance (verified May 2026).
#   2. Delisted / demerged tickers that return empty data are EXCLUDED.
#   3. When a company renames, use the CURRENT yfinance ticker.
#   4. Tickers with & and - that work on yfinance are kept as-is.
#
# EXCLUDED (confirmed dead on yfinance as of May 2026):
#   TATAMOTORS.NS   — demerged into TMCV.NS + TMPV.NS (Oct 2024)
#   TATAMTRDVR.NS   — DVR share, demerged along with TATAMOTORS
#   ADANIGAS.NS     — use ATGL.NS instead (yfinance recognises ATGL)
#   AMARAJABAT.NS   — old name, delisted (now ARE&M but has limited history)
#   MCDOWELL-N.NS   — delisted / not found on yfinance
#   HEXAWARE.NS     — delisted (taken private 2020)
#   IBULHSGFIN.NS   — delisted / not found
#   IBVENTURES.NS   — delisted / not found
#   ISEC.NS         — delisted (ICICI Securities merged with ICICIBANK)
#   JUBILANT.NS     — ticker not found (JUBLFOOD.NS is separate, kept)
#   PEL.NS          — Piramal Enterprises delisted / not found
#   STRTECH.NS      — Sterlite Tech, not found on yfinance
#   DHANI.NS        — delisted / not found
#
# CORRUPT PRICE DATA (excluded — user chose option A):
#   PATANJALI.NS    — yfinance auto_adjust failure: -93.9% then +201.7% monthly
#   FCONSUMER.NS    — crashes from ₹41 to ₹0.31 (data error or penny stock)
# ─────────────────────────────────────────────────────────────────────────────

NSE200 = [
    "AARTIIND.NS",
    "ABB.NS",
    "ABBOTINDIA.NS",
    "ABCAPITAL.NS",
    "ABFRL.NS",
    "ACC.NS",
    "ADANIENSOL.NS",
    "ADANIENT.NS",
    "ADANIGREEN.NS",
    "ADANIPORTS.NS",
    "ADANIPOWER.NS",
    "AJANTPHARM.NS",
    "ALKEM.NS",
    "AMBUJACEM.NS",
    "APLAPOLLO.NS",
    "APLLTD.NS",
    "APOLLOHOSP.NS",
    "APOLLOTYRE.NS",
    "ARE&M.NS",
    "ASHOKLEY.NS",
    "ASIANPAINT.NS",
    "ASTRAL.NS",
    "ATGL.NS",          # yfinance name for Adani Total Gas (was ADANIGAS)
    "AUBANK.NS",
    "AUROPHARMA.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJAJFINSV.NS",
    "BAJAJHFL.NS",
    "BAJAJHLDNG.NS",
    "BAJFINANCE.NS",
    "BALKRISIND.NS",
    "BANDHANBNK.NS",
    "BANKBARODA.NS",
    "BANKINDIA.NS",
    "BATAINDIA.NS",
    "BBTC.NS",
    "BDL.NS",
    "BEL.NS",
    "BERGEPAINT.NS",
    "BHARATFORG.NS",
    "BHARTIARTL.NS",
    "BHEL.NS",
    "BIOCON.NS",
    "BLUESTARCO.NS",
    "BOSCHLTD.NS",
    "BPCL.NS",
    "BRITANNIA.NS",
    "BSE.NS",
    "CANBK.NS",
    "CASTROLIND.NS",
    "CESC.NS",
    "CGPOWER.NS",
    "CHOLAFIN.NS",
    "CIPLA.NS",
    "CLEAN.NS",
    "COALINDIA.NS",
    "COCHINSHIP.NS",
    "COFORGE.NS",
    "COLPAL.NS",
    "CONCOR.NS",
    "COROMANDEL.NS",
    "CROMPTON.NS",
    "CUB.NS",
    "CUMMINSIND.NS",
    "DABUR.NS",
    "DALBHARAT.NS",
    "DEEPAKNTR.NS",
    "DIVISLAB.NS",
    "DIXON.NS",
    "DLF.NS",
    "DMART.NS",
    "DRREDDY.NS",
    "EDELWEISS.NS",
    "EICHERMOT.NS",
    "EMAMILTD.NS",
    "ENDURANCE.NS",
    "ENGINERSIN.NS",
    "ENRIN.NS",
    "ESCORTS.NS",
    "ETERNAL.NS",
    "EXIDEIND.NS",
    "FEDERALBNK.NS",
    "FORTIS.NS",
    "FRETAIL.NS",
    "GAIL.NS",
    "GICRE.NS",
    "GLAND.NS",
    "GLENMARK.NS",
    "GMRAIRPORT.NS",
    "GODFRYPHLP.NS",
    "GODREJAGRO.NS",
    "GODREJCP.NS",
    "GODREJIND.NS",
    "GODREJPROP.NS",
    "GRAPHITE.NS",
    "GRASIM.NS",
    "GROWW.NS",
    "GSPL.NS",
    "GUJGASLTD.NS",
    "GVT&D.NS",
    "HAL.NS",
    "HAVELLS.NS",
    "HCLTECH.NS",
    "HDFCAMC.NS",
    "HDFCBANK.NS",
    "HDFCLIFE.NS",
    "HEG.NS",
    "HEROMOTOCO.NS",
    "HINDALCO.NS",
    "HINDCOPPER.NS",
    "HINDPETRO.NS",
    "HINDUNILVR.NS",
    "HINDZINC.NS",
    "HUDCO.NS",
    "HYUNDAI.NS",
    "ICICIAMC.NS",
    "ICICIBANK.NS",
    "ICICIGI.NS",
    "ICICIPRULI.NS",
    "IDBI.NS",
    "IDEA.NS",
    "IDFCFIRSTB.NS",
    "IEX.NS",
    "IGL.NS",
    "INDHOTEL.NS",
    "INDIAMART.NS",
    "INDIANB.NS",
    "INDIGO.NS",
    "INDUSINDBK.NS",
    "INDUSTOWER.NS",
    "INFY.NS",
    "IOC.NS",
    "IPCALAB.NS",
    "IRCTC.NS",
    "IREDA.NS",
    "IRFC.NS",
    "ITC.NS",
    "JINDALSTEL.NS",
    "JIOFIN.NS",
    "JSWENERGY.NS",
    "JSWSTEEL.NS",
    "JUBLFOOD.NS",
    "KALYANKJIL.NS",
    "KEI.NS",
    "KOTAKBANK.NS",
    "KPITTECH.NS",
    "LALPATHLAB.NS",
    "LAURUSLABS.NS",
    "LENSKART.NS",
    "LGEINDIA.NS",
    "LICHSGFIN.NS",
    "LICI.NS",
    "LODHA.NS",
    "LT.NS",
    "LTF.NS",
    "LTIM.NS",
    "LTTS.NS",
    "LUPIN.NS",
    "M&M.NS",
    "M&MFIN.NS",
    "MANAPPURAM.NS",
    "MANKIND.NS",
    "MARICO.NS",
    "MARUTI.NS",
    "MAXHEALTH.NS",
    "MAZDOCK.NS",
    "MCX.NS",
    "METROPOLIS.NS",
    "MFSL.NS",
    "MGL.NS",
    "MOTHERSON.NS",
    "MOTILALOFS.NS",
    "MPHASIS.NS",
    "MRF.NS",
    "MRPL.NS",
    "MUTHOOTFIN.NS",
    "NAM-INDIA.NS",
    "NATCOPHARM.NS",
    "NATIONALUM.NS",
    "NAUKRI.NS",
    "NAVINFLUOR.NS",
    "NESTLEIND.NS",
    "NHPC.NS",
    "NIACL.NS",
    "NMDC.NS",
    "NTPC.NS",
    "NYKAA.NS",
    "OBEROIRLTY.NS",
    "OFSS.NS",
    "ONGC.NS",
    "PAGEIND.NS",
    "PAYTM.NS",
    "PERSISTENT.NS",
    "PETRONET.NS",
    "PFC.NS",
    "PFIZER.NS",
    "PGHH.NS",
    "PHOENIXLTD.NS",
    "PIDILITIND.NS",
    "PIIND.NS",
    "PNB.NS",
    "PNBHOUSING.NS",
    "POLICYBZR.NS",
    "POLYCAB.NS",
    "POWERGRID.NS",
    "POWERINDIA.NS",
    "PREMIERENE.NS",
    "PRESTIGE.NS",
    "QUESS.NS",
    "RADICO.NS",
    "RAJESHEXPO.NS",
    "RAMCOCEM.NS",
    "RBLBANK.NS",
    "RECLTD.NS",
    "RELIANCE.NS",
    "RVNL.NS",
    "SAIL.NS",
    "SANOFI.NS",
    "SBICARD.NS",
    "SBILIFE.NS",
    "SBIN.NS",
    "SHREECEM.NS",
    "SHRIRAMFIN.NS",
    "SIEMENS.NS",
    "SOLARINDS.NS",
    "SONACOMS.NS",
    "SRF.NS",
    "SUNPHARMA.NS",
    "SUNTV.NS",
    "SUPREMEIND.NS",
    "SUZLON.NS",
    "SWIGGY.NS",
    "SYNGENE.NS",
    "TATACAP.NS",
    "TATACHEM.NS",
    "TATACOMM.NS",
    "TATACONSUM.NS",
    "TATAELXSI.NS",
    "TATAINVEST.NS",
    "TATAPOWER.NS",
    "TATASTEEL.NS",
    "TCS.NS",
    "TECHM.NS",
    "TIINDIA.NS",
    "TITAN.NS",
    "TMCV.NS",         # Tata Motors Commercial Vehicles (post-demerger)
    "TMPV.NS",         # Tata Motors Passenger Vehicles (post-demerger)
    "TORNTPHARM.NS",
    "TORNTPOWER.NS",
    "TRENT.NS",
    "TRIDENT.NS",
    "TVSMOTOR.NS",
    "UBL.NS",
    "ULTRACEMCO.NS",
    "UNIONBANK.NS",
    "UNITDSPR.NS",
    "UPL.NS",
    "VARROC.NS",
    "VBL.NS",
    "VEDL.NS",
    "VGUARD.NS",
    "VMM.NS",
    "VOLTAS.NS",
    "WAAREEENER.NS",
    "WHIRLPOOL.NS",
    "WIPRO.NS",
    "YESBANK.NS",
    "ZEEL.NS",
    "ZYDUSLIFE.NS",
]

# Tickers with confirmed corrupt yfinance price data.
# These are excluded from the main NSE200 list and from price downloads.
# Documented here for traceability.
EXCLUDED_CORRUPT = [
    "PATANJALI.NS",    # yfinance auto_adjust failure: -93.9% then +201.7% monthly
    "FCONSUMER.NS",    # price crash from ₹41 to ₹0.31 (data error)
]
