# nse200_tickers.py — verified NSE200 tickers in yfinance format
NSE200 = [
    # Banking
    "HDFCBANK.NS","ICICIBANK.NS","KOTAKBANK.NS","AXISBANK.NS","SBIN.NS",
    "BANKBARODA.NS","PNB.NS","CANBK.NS","INDIANB.NS","UNIONBANK.NS",
    "BANDHANBNK.NS","FEDERALBNK.NS","IDFCFIRSTB.NS","AUBANK.NS",
    # NBFC / Insurance / Capital Markets
    "BAJFINANCE.NS","BAJAJFINSV.NS","SHRIRAMFIN.NS","CHOLAFIN.NS","MUTHOOTFIN.NS",
    "PFC.NS","RECLTD.NS","IRFC.NS","LICHSGFIN.NS","SBILIFE.NS",
    "HDFCLIFE.NS","ICICIGI.NS","LICI.NS","BSE.NS","CDSL.NS","CAMS.NS",
    # IT
    "TCS.NS","INFY.NS","HCLTECH.NS","WIPRO.NS","TECHM.NS",
    "LTIM.NS","MPHASIS.NS","COFORGE.NS","PERSISTENT.NS","OFSS.NS",
    # Energy
    "RELIANCE.NS","ONGC.NS","BPCL.NS","IOC.NS","COALINDIA.NS",
    "NTPC.NS","POWERGRID.NS","TATAPOWER.NS","ADANIGREEN.NS","ADANIPORTS.NS",
    "ADANIENT.NS","GAIL.NS","PETRONET.NS","OIL.NS","TORNTPOWER.NS",
    # FMCG
    "HINDUNILVR.NS","ITC.NS","NESTLEIND.NS","BRITANNIA.NS","DABUR.NS",
    "MARICO.NS","COLPAL.NS","GODREJCP.NS","EMAMILTD.NS","TATACONSUM.NS",
    "VBL.NS","RADICO.NS","UBL.NS",
    # Auto  (corrected symbols)
    "MARUTI.NS","TATAMOTORS.NS","M&M.NS","BAJAJ-AUTO.NS","EICHERMOT.NS",
    "TVSMOTOR.NS","HEROMOTOCO.NS","BOSCHLTD.NS","MOTHERSON.NS","BALKRISIND.NS",
    "APOLLOTYRE.NS","EXIDEIND.NS","ASHOKLEY.NS","MINDINDS.NS",
    # Pharma  (corrected symbols)
    "SUNPHARMA.NS","DRREDDY.NS","CIPLA.NS","DIVISLAB.NS","LUPIN.NS",
    "TORNTPHARM.NS","AUROPHARMA.NS","ALKEM.NS","ABBOTINDIA.NS",
    "APOLLOHOSP.NS","MAXHEALTH.NS","FORTIS.NS","LALPATHLAB.NS",
    # Metals
    "TATASTEEL.NS","JSWSTEEL.NS","HINDALCO.NS","VEDL.NS","SAIL.NS",
    "NMDC.NS","NATIONALUM.NS","APLAPOLLO.NS","RATNAMANI.NS",
    # Cement
    "ULTRACEMCO.NS","GRASIM.NS","SHREECEM.NS","AMBUJACEM.NS","ACC.NS",
    "DALMIACEM.NS","RAMCOCEM.NS","JKCEMENT.NS",
    # Capital Goods / Infra
    "LT.NS","SIEMENS.NS","ABB.NS","BHEL.NS","BEL.NS","HAL.NS",
    "HAVELLS.NS","VOLTAS.NS","CUMMINSIND.NS","GMRAIRPORT.NS","NCC.NS",
    # Chemicals  (corrected symbols)
    "PIDILITIND.NS","DEEPAKNTR.NS","NAVINFLUOR.NS","AARTIIND.NS",
    "GALAXYSURF.NS","FLUOROCHEM.NS","BERGEPAINT.NS",
    # Consumer Discretionary  (corrected symbols)
    "DMART.NS","TRENT.NS","TITAN.NS","KALYANKJIL.NS",
    "JUBLFOOD.NS","DIXON.NS","AMBER.NS","PVRINOX.NS","LODHA.NS",
    # Telecom
    "BHARTIARTL.NS","INDUSTOWER.NS","TATACOMM.NS",
    # Logistics
    "INDIGO.NS","BLUEDART.NS","DELHIVERY.NS","CONCOR.NS",
    # Real Estate
    "DLF.NS","GODREJPROP.NS","PRESTIGE.NS","BRIGADE.NS",
    "OBEROIRLTY.NS","PHOENIXLTD.NS",
    # Paints
    "ASIANPAINT.NS","KANSAINER.NS",
    # Agri  (corrected symbols)
    "UPL.NS","PIIND.NS","COROMANDEL.NS","CHAMBLFERT.NS",
    # Diversified
    "SBICARD.NS","ABCAPITAL.NS","ANGELONE.NS","MFSL.NS","CANFINHOME.NS",
    "PNBHOUSING.NS","SCHAEFFLER.NS","TIMKEN.NS","ASTRAL.NS",
    "SUNTV.NS","ZEEL.NS","RAYMOND.NS",
]
# Deduplicate preserving order
seen = set()
NSE200 = [t for t in NSE200 if not (t in seen or seen.add(t))]

if __name__ == "__main__":
    print(f"Total tickers: {len(NSE200)}")
